//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SED.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evaluacion
    {
        public int Id_Evaluacion { get; set; }
        public Nullable<int> fk_Id_Evaluador { get; set; }
        public Nullable<int> fk_Id_Docente { get; set; }
        public Nullable<System.DateTime> fechaEvaluacion { get; set; }
        public string estado { get; set; }
    
        public virtual Docente Docente { get; set; }
        public virtual Evaluador Evaluador { get; set; }
    }
}
