//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedSocial.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RED_SOCIALEntities : DbContext
    {
        public RED_SOCIALEntities()
            : base("name=RED_SOCIALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PERSONA> PERSONA { get; set; }
        public virtual DbSet<ROL> ROL { get; set; }
    
        public virtual int AGREGAR_USUARIO(string nOMBRE, string cORREO, string cONTRASENIA)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var cORREOParameter = cORREO != null ?
                new ObjectParameter("CORREO", cORREO) :
                new ObjectParameter("CORREO", typeof(string));
    
            var cONTRASENIAParameter = cONTRASENIA != null ?
                new ObjectParameter("CONTRASENIA", cONTRASENIA) :
                new ObjectParameter("CONTRASENIA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AGREGAR_USUARIO", nOMBREParameter, cORREOParameter, cONTRASENIAParameter);
        }
    
        public virtual ObjectResult<PERSONA> AUTENTICAR(string cORREO, string cONTRA)
        {
            var cORREOParameter = cORREO != null ?
                new ObjectParameter("CORREO", cORREO) :
                new ObjectParameter("CORREO", typeof(string));
    
            var cONTRAParameter = cONTRA != null ?
                new ObjectParameter("CONTRA", cONTRA) :
                new ObjectParameter("CONTRA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PERSONA>("AUTENTICAR", cORREOParameter, cONTRAParameter);
        }
    
        public virtual ObjectResult<PERSONA> AUTENTICAR(string cORREO, string cONTRA, MergeOption mergeOption)
        {
            var cORREOParameter = cORREO != null ?
                new ObjectParameter("CORREO", cORREO) :
                new ObjectParameter("CORREO", typeof(string));
    
            var cONTRAParameter = cONTRA != null ?
                new ObjectParameter("CONTRA", cONTRA) :
                new ObjectParameter("CONTRA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PERSONA>("AUTENTICAR", mergeOption, cORREOParameter, cONTRAParameter);
        }
    }
}
